---

- name: Install Dovecot APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ dovecot__base_packages }}'
  when: ansible_pkg_mgr == 'apt'